Enhancement/adding infofile validator
IPG-Automotive-UK/infofile-utils pull request #17
Opened 2024-03-22 14:29 UTC by arpadlomenipg

Contributes to[ TD-2263](https://sce.myjetbrains.com/youtrack/issue/TD-2263/VIRTO.TEST-errors-when-Vehicle-folder-contains-temp-files)

## Changes

A supporting function for [ TD-2263](https://sce.myjetbrains.com/youtrack/issue/TD-2263/VIRTO.TEST-errors-when-Vehicle-folder-contains-temp-files), but could be used in other applications too later.

It adds an infofile validator to the infofile-utils. Additionally, I infofiles into the repository for the unit tests. The current options to for infofile validations are : 
* "Vehicle" (looks either for Car, Motorcycle or Truck infofile)
* "TestRun" (looks for TestRun infofile)
* "Road" (looks for Road infofile)
* "Model" (looks for anything else, which is a valid infofile, be that a Trailer, a sensor model, etc.

The basis of the validation is always the "FileIdent" property of the infofile, an appropriate RegEx search is carried out for each of the options listed above.

## Dependencies

## UI/UX

## Testing notes

## Author checklist before assigning a reviewer

- [ ] Reviewed my own code-diff.
- [ ] Branch has been run in docker.
- [ ] PR assigned to me or an appropriate delegate.
- [ ] Relevant labels added to the PR.
- [ ] Appropriate tests have been added.
- [ ] Lint and test workflows pass.

2024-03-25 08:18 UTC, mattcorner requested changes
Nice work, left some suggestions.

2024-03-25 08:18 UTC, mattcorner commented on src/isValidInfoFile.js
> +        }
Generally speaking, if else statements already operate on a boolean, so there is no need to return booleans from within. Instead just return the statement. Same applies to the rest of the switch cases.

```suggestion
        return fileIdent.match(/^CarMaker-Car\s\d{2}$/) ||
          fileIdent.match(/^CarMaker-Truck\s\d{2}$/) ||
          fileIdent.match(/^CarMaker-Motorcycle\s\d{2}$/)
```

Granted here you are also handling infofile.delete() which I'll comment on seperately.

2024-03-25 08:18 UTC, mattcorner commented on src/isValidInfoFile.js
> +  }
You basically always want to delete the infofile handle before returning the result or an error. Hence your code is littered with calls to `infofile.delete()`. There is a third step to a `try {} catch {}` called finally which handles this exact case. It runs regardless of whether we return a result or throw an error.

Hence you can do:
```ts
try {
  // ...
} catch (err) {
   // ...
} finally {
   infofile.delete();
}

2024-03-25 08:18 UTC, mattcorner commented on src/index.js
> +  ...require("./isValidInfoFile"),
We should update the README.md now that we are exporting an additional method from the package.

2024-03-25 08:18 UTC, mattcorner commented on src/__tests__/isValidInfoFile.test.js
> +  });
There are a lot of similar tests in this file that basically say "For this file and infofile type, check that the result is true".

Check out parameterised tests using [`test.each`](https://vitest.dev/api/#test-each). You basically create a matrix of test data, and then write one test.

2024-03-25 08:18 UTC, mattcorner commented on src/isValidInfoFile.js
> +  }
I expected to be able to call this method without a infofile type. a.k.a I just want to check its an infofile but I don't care what type. I think we did discuss this but I guess it got lost in the detail.

2024-03-25 08:18 UTC, mattcorner commented on src/__tests__/isValidInfoFile.test.js
> +  });
Can you describe the path through the code that gets us here? Reading the code it looks like it would error. 

I presume the infofile handle does construct, and get FileIdent actually returns an empty string or something?

2024-03-25 11:14 UTC, arpadlomenipg commented on src/isValidInfoFile.js
> +        }
The if-else statements are operating on vectors (.match returns that), so this solution cannot be used here. However, with the elimination of all the infofile.delete-s, I can use the ? : operator now, which will make the code a bit more compact

2024-03-25 14:10 UTC, mattcorner commented on src/isValidInfoFile.js
> +        }
Makes sense

2024-03-25 15:44 UTC, arpadlomenipg commented on src/__tests__/isValidInfoFile.test.js
> +  });
yes, that's exactly what happens

2024-03-25 16:46 UTC, arpadlomenipg commented on src/isValidInfoFile.js
> +  }
I must have missed that then, added this to the code

2024-03-25 17:03 UTC, arpadlomenipg commented on src/index.js
> +  ...require("./isValidInfoFile"),
updated the README, thanks for the feedback!

2024-03-26 09:08 UTC, mattcorner requested changes
Minor typo in the README.

2024-03-26 09:08 UTC, mattcorner commented on README.md
> +const file = C:\infofiles\infofile
```suggestion
const file = "C:\infofiles\infofile";
```

2024-03-26 09:15 UTC, mattcorner commented
I've published a pre-release for you so that you can start making use if it in VIRTO as a final test: @ipguk/infofile-utils@1.1.0-0

2024-03-26 13:37 UTC, arpadlomenipg commented on README.md
> +const file = C:\infofiles\infofile
I will fix this in all other places of the README too

2024-03-26 17:23 UTC, mattcorner requested changes
failing CI

2024-03-26 17:29 UTC, arpadlomenipg commented
Sorry, turns out file names are case insensitive on windows, but not on linux, hence the unexpected unit test fail here

I added a bunch of new types, removed the type "Model", changed the RegEx search pattern when calling without type

2024-03-27 12:10 UTC, arpadlomenipg commented
I am done with the testing in Virto, I have not encountered any problems. I looked through the code, this implementation has all the necessary types to use it in Virto-apps, where currently an infofile validation is being used with a local implementation, so I have no plans to expand it with more types now.

2024-03-27 12:12 UTC, mattcorner approved these changes
lgtm. merge the PR and drop me a message to do the release

2024-03-27 12:34 UTC, merged